apiVersion: v1
kind: Secret
metadata:
  name: ems-secrets
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  mongodb-uri: bW9uZ29kYitzcnY6Ly91c2VybmFtZTpwYXNzd29yZEBjbHVzdGVyLm1vbmdvZGIubmV0L0VNU19EYXRhYmFzZQ==
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl
  admin-password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-config
data:
  environment: "production"
  mongodb-database: "EMS_Database"
  redis-host: "redis-service"
  redis-port: "6379"
  log-level: "INFO"
  rate-limit-requests: "100"
  rate-limit-window: "60"
